version: '3.7'
services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_DATABASE: ZeslaGroup
  web:
    build:
      context: app
      dockerfile: Dockerfile
    volumes:
      - ./app/:/app
    ports:
      - 5000:5000
    env_file:
      - .env
    links:
      - mongodb

